version: '3.9'

services:
  social_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=social-dev
    ports:
      - '5432:5432'
    restart: always
    networks:
      - social
  social_test:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=social-test
    ports:
      - '5435:5432'
    restart: always
    networks:
      - social

networks:
  social:
